<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <RootNamespace>Contacts_App</RootNamespace>
    <AssemblyName>Contacts App</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Default PFP.jpg" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Contacts App - Bussiness Layer\Contacts App - Bussiness Layer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Default PFP.jpg" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator></Generator>
    </EmbeddedResource>
  </ItemGroup>

</Project>